# Generated by Django 4.2.20 on 2025-04-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("recruiter", "Recruiter"), ("applicant", "Applicant")],
                max_length=20,
            ),
        ),
    ]
