# Generated by Django 4.2.20 on 2025-04-14 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicUserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                (
                    "looking_for",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("full_time", "Full Time"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering"),
                            ("management", "Management"),
                            ("research", "Research"),
                            ("economins", "Economics"),
                            ("teaching", "Teaching"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bio", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=20)),
                ("job_role", models.CharField(max_length=20)),
                ("experience", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
